apiVersion: v1
kind: Service
metadata:
  name: tomcat-mount
  namespace: default
  labels:
    k8s-app: tomcat-mount
spec:
  ports:
    - name: tcp-8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 
    - name: tcp-8443-8443
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 
  type: NodePort
  selector:
    k8s-app: tomcat-mount 
